Develop
Dimm-S/java-explore-with-me pull request #7
Opened 2023-01-17 21:54 UTC by Dimm-S

2023-01-18 18:02 UTC, EvgenyKoptubenko commented
Не проходят все проверки 
Explore With Me API Tests / build / build-ewm (pull_request) Failing after 1m

2023-01-18 18:13 UTC, EvgenyKoptubenko commented
приложение не запускается из коробки Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "root"

2023-01-18 18:14 UTC, EvgenyKoptubenko requested changes
Подскажи как запустить приложение. На текущий момент если из коробки запустить через docker compose, то не стартует

2023-01-19 13:14 UTC, Dimm-S commented
> Подскажи как запустить приложение. На текущий момент если из коробки запустить через docker compose, то не стартует

Может проблема в логине/пароле к БД? Попробуй поменять в application.properties на свои.

2023-01-19 13:23 UTC, Dimm-S commented
> Не проходят все проверки Explore With Me API Tests / build / build-ewm (pull_request) Failing after 1m

Валятся только два последних теста на сервисе статистики, разбираюсь. Основной сервис все проверки проходит, на на гитхабе всё в докер собирается.

2023-01-21 19:57 UTC, EvgenyKoptubenko commented
Не проходит проверка на GitHub
Explore With Me API Tests / build / build-ewm (pull_request) Failing after 1m

2023-01-21 19:59 UTC, EvgenyKoptubenko requested changes
проект так и не стартует из коробки.
Сборка и запуск проекта должен быть такой: mvn clean package
Потом запуск docker compose.
База данных у другого разработчика стоять не должна, она должна запускаться через докер.

Попробуй такой docker compose:
`version: '3.1'
services:
  stats-server:
    build: stats
    container_name: ewm-stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SERVER_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=817b62

  stats-db:
    image: postgres:14-alpine
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=817b62

  ewm-service:
    build: ewm
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=817b62
      - STATS-SERVER.URL=http://stats-server:9090
  ewm-db:
    image: postgres:14-alpine
    container_name: postgres-ewm-main
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=817b62
`

2023-01-23 19:59 UTC, EvgenyKoptubenko commented on ewm-service/src/main/java/ru/practicum/explore/user/UserAdminController.java
> +    public void deleteUser(@PathVariable Long userId) {
Если попробовать удалить несуществующего пользователя, то приходит 500-я ошибка
{
	"timestamp": "2023-01-23T19:54:54.357+00:00",
	"status": 500,
	"error": "Internal Server Error",
	"path": "/admin/users/12"
}
Это не должно быть внутренней ошибкой сервера, а клиент должен понять, что такого пользователя нет.

2023-01-23 20:17 UTC, EvgenyKoptubenko commented on ewm-service/src/main/java/ru/practicum/explore/user/UserAdminController.java
> +    public UserDto saveUser(
Если отправить неверные данные, то клиенту приходит стектрейс

{
	"errors": [
		"org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:141)",
		"org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:122)",
		"org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:179)",
		"org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:146)",
		"org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)",
		"org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)",
		"org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)",
		"org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)",
		"org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071)",
		"org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964)",
		"org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)",
		"org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)",
		"javax.servlet.http.HttpServlet.service(HttpServlet.java:696)",
		"org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)",
		"javax.servlet.http.HttpServlet.service(HttpServlet.java:779)",
		"org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)",
		"org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)",
		"org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)",
		"org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)",
		"org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)",
		"org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)",
		"org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)",
		"org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)",
		"org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)",
		"org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)",
		"org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)",
		"org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)",
		"org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)",
		"org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)",
		"org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)",
		"org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)",
		"org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)",
		"org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)",
		"org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)",
		"org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)",
		"org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)",
		"org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)",
		"org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)",
		"org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)",
		"org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)",
		"org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)",
		"org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)",
		"org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)",
		"org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)",
		"org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)",
		"org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)",
		"org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)",
		"org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)",
		"org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)",
		"org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)",
		"org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)",
		"java.base/java.lang.Thread.run(Thread.java:829)"
	],
	"message": "Validation failed for argument [0] in public ru.practicum.ewm.user.dto.UserDto ru.practicum.ewm.user.controller.AdminUserController.createUser(ru.practicum.ewm.user.dto.NewUserDto): [Field error in object 'newUserDto' on field 'email': rejected value [email3email.com]; codes [Pattern.newUserDto.email,Pattern.email,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [newUserDto.email,email]; arguments []; default message [email],[Ljavax.validation.constraints.Pattern$Flag;@4afc75b6,^(.+)@(\\S+)$]; default message [Must be formatted: mailName@domain]] ",
	"reason": "Method argument not valid.",
	"status": "BAD_REQUEST",
	"timestamp": "2023-01-23 20:16:19"
}

2023-01-23 20:17 UTC, EvgenyKoptubenko commented on ewm-service/src/main/java/ru/practicum/explore/user/UserAdminController.java
> +    public void deleteUser(@PathVariable Long userId) {
При удалении тоже приходит стектрейс, который клиенту не нужен
{
	"errors": [
		"ru.practicum.ewm.user.service.UserServiceImpl.deleteUser(UserServiceImpl.java:54)",
		"ru.practicum.ewm.user.controller.AdminUserController.deleteUser(AdminUserController.java:45)",
		"ru.practicum.ewm.user.controller.AdminUserController$$FastClassBySpringCGLIB$$9fec253d.invoke(<generated>)",
		"org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)",
		"org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)",
		"org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)",
		"org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)",
		"org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:123)",
		"org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)",
		"org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)",
		"org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)",
		"ru.practicum.ewm.user.controller.AdminUserController$$EnhancerBySpringCGLIB$$c6c1b137.deleteUser(<generated>)",
		"java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
		"java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
		"java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
		"java.base/java.lang.reflect.Method.invoke(Method.java:566)",
		"org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)",
		"org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)",
		"org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)",
		"org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)",
		"org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)",
		"org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)",
		"org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071)",
		"org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964)",
		"org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)",
		"org.springframework.web.servlet.FrameworkServlet.doDelete(FrameworkServlet.java:931)",
		"javax.servlet.http.HttpServlet.service(HttpServlet.java:702)",
		"org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)",
		"javax.servlet.http.HttpServlet.service(HttpServlet.java:779)",
		"org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)",
		"org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)",
		"org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)",
		"org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)",
		"org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)",
		"org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)",
		"org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)",
		"org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)",
		"org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)",
		"org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)",
		"org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)",
		"org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)",
		"org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)",
		"org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)",
		"org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)",
		"org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)",
		"org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)",
		"org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)",
		"org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)",
		"org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)",
		"org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)",
		"org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)",
		"org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)",
		"org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)",
		"org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)",
		"org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)",
		"org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)",
		"org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)",
		"org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)",
		"org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)",
		"org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)",
		"org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)",
		"org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)",
		"org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)",
		"org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)",
		"org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)",
		"java.base/java.lang.Thread.run(Thread.java:829)"
	],
	"message": "User id=12 was not found",
	"reason": "Entity not found.",
	"status": "NOT_FOUND",
	"timestamp": "2023-01-23 20:17:28"
}

2023-01-23 20:22 UTC, EvgenyKoptubenko commented on ewm-service/src/main/java/ru/practicum/explore/event/EventController.java
> +    public List<EventShortDto> getEvents(
Если отправить такой запрос curl --request GET \
  --url 'http://localhost:8080/events?from=0&size=1' \
  --header 'Content-Type: multipart/form-data' \
  --form =
То падает 

{
	"errors": [
		"org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:785)",
		"org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711)",
		"org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:602)",
		"ru.practicum.ewm.event.client.BaseClient.makeAndSendRequest(BaseClient.java:36)",
		"ru.practicum.ewm.event.client.BaseClient.post(BaseClient.java:24)",
		"ru.practicum.ewm.event.client.EventClient.postHit(EventClient.java:30)",
		"ru.practicum.ewm.event.controller.PublicEventController.getEvents(PublicEventController.java:54)",
		"java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
		"java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
		"java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
		"java.base/java.lang.reflect.Method.invoke(Method.java:566)",
		"org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)",
		"org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)",
		"org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:799)",
		"org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)",
		"org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)",
		"org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:123)",
		"org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)",
		"org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)",
		"org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)",
		"ru.practicum.ewm.event.controller.PublicEventController$$EnhancerBySpringCGLIB$$591c5c4b.getEvents(<generated>)",
		"java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
		"java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
		"java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
		"java.base/java.lang.reflect.Method.invoke(Method.java:566)",
		"org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)",
		"org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)",
		"org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)",
		"org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)",
		"org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)",
		"org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)",
		"org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071)",
		"org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964)",
		"org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)",
		"org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)",
		"javax.servlet.http.HttpServlet.service(HttpServlet.java:670)",
		"org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)",
		"javax.servlet.http.HttpServlet.service(HttpServlet.java:779)",
		"org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)",
		"org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)",
		"org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)",
		"org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)",
		"org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)",
		"org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)",
		"org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)",
		"org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)",
		"org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)",
		"org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)",
		"org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)",
		"org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)",
		"org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)",
		"org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)",
		"org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)",
		"org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)",
		"org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)",
		"org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)",
		"org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)",
		"org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)",
		"org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)",
		"org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)",
		"org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)",
		"org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)",
		"org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)",
		"org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)",
		"org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)",
		"org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)",
		"org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)",
		"org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)",
		"org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)",
		"org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)",
		"org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)",
		"org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)",
		"org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)",
		"org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)",
		"java.base/java.lang.Thread.run(Thread.java:829)"
	],
	"message": "org.springframework.web.client.ResourceAccessException",
	"reason": "Error occurred.",
	"status": "INTERNAL_SERVER_ERROR",
	"timestamp": "2023-01-23 20:18:35"
}

2023-01-23 20:28 UTC, EvgenyKoptubenko commented on docker-compose.yml
> +      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
Тут нужно добавить       - SERVER_PORT=9090
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password

2023-01-23 20:33 UTC, EvgenyKoptubenko commented on docker-compose.yml
А тут это 
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password

2023-01-23 20:34 UTC, EvgenyKoptubenko commented
Пока не пройдут проверки на GitHub, принять работу не могу 

Explore With Me API Tests / build / build-ewm (pull_request) Failing after 1m

2023-01-23 20:39 UTC, EvgenyKoptubenko requested changes
Нужно убрать стектрейсы из сообщений для клиента.
Нужно поправить docker-compose - я написал что нужно добавить
Так же не проходят все проверки в github

2023-04-15 14:53 UTC, closed without merging